pkpndLiZ/actitvity-tracking-web

- components/NavBar.jsx
- styles/globals.css
AT-2
Dev Navbar and Navbar CSS
> feat: dev Navbar and Navbar Css

- components/EditActivity.jsx
- styles/EditActivity.scss
- styles/globals.scss
[AT-11]
- Create EditActivity component
- Add style to EditActivity component
- Import style to global.css file
> [AT-11] Create EditActivity component

- components/HomeContent.jsx
- components/ProfileContent.jsx
- pages/profile.jsx
at-18
- สร้าง profilepage และใส่ layout 
> [AT-18] Create profile page and add style

- components/CreateActivity.jsx
- utils/axiosInstance.js
[AT-20] prepare image for store on cloud
- convert image file to base64
> [AT-20] convert image file to base64

- components/AlertBox.jsx
- package-lock.json
- package.json
at-21
- เพิ่ม alert box เวลา alert จะขึ้นที่ด้านซ้ายล่าง
> [AT-21] Create Alert Box

- components/CardItem.jsx
- components/CardMenu.jsx
- components/EditActivity.jsx
- components/HomeContent.jsx
- next.config.js
at-19
- pass data จากหน้า homecontent ให้แสดงใน editactivity component เวลาคลิก edit menu
> [AT-19] pass data from card to editactivity component

- components/EditActivity.jsx
- styles/CreateActivity.scss
- styles/EditActivity.scss
at-24
- pass imageurl from card to editactivity component
- change height of description input to fit to form
> [AT-24] pass image url and fix height of description

- utils/axiosInstance.js
at-22] fix bug frontend, backend communication
ใส่ตรงนี้
- get rid of timeout
- frontend and backend can communicate normally
> [at-22] fix bug frontend, backend communication

- components/EditProfile.jsx
at-30
- สร้าง editprofile component 
> [AT-30] Create EditProfile component

- components/NavBar.jsx
at-31
- เพิ่มปุ่ม logout และ profile ตรง navbar ถ้า user login ถ้า user ไม่ล็อกอินจะ แสดง login or register
> [AT-31] add logout and profile on navbar

- pages/register.jsx
at-36
- แก้ register form ให้รับแค่ email กับ password
> [AT-36] edit register form

- pages/login.jsx
- utils/axiosInstance.js
- edit token storage from session to local storage
- เพิ่มปุ่มกด..etc
> [AT-37] edit token storage

- components/ProfileContent.jsx
- pages/register.jsx
at-35
- เพิ่ม api ใน register page ให้ส่งข้อมูลไปที่ backend อย่างถูกต้อง
> [AT-35] Implement POST api in register page

- components/CardMenu.jsx
- components/SideBar.jsx
at-32
- เช็คเงื่อนไขปุ่ม new post ถ้า user ไม่ได้ login อยู่ให้เด้งไปหน้า login
- เช็คเงื่อนไขปุ่ม edit และ delete ถ้า userId ไม่ตรงจะไม่สามารถ edit หรือ delete ได้ และ ถ้าไม่ได้ login อยู่จะเด้งไปที่หน้า login
> [AT-32] check login and cardmenu condition

- components/CardItem.jsx
- components/CardMenu.jsx
- components/EditProfile.jsx
- components/NavBar.jsx
- components/ProfileContent.jsx
at-43
- เพิ่ม condition ให้ carditem ถ้า userid ไม่ตรงกับการ์ดจะไม่สามารถมองเห็น  cardmenu ได้
- เคลีย condition เก่าออกจาก cardmenu 
> [AT-43] Add condition to show cardmenu

- components/ProfileContent.jsx
at-44
- ใส่ props ให้ cardcomponent ใน profile
> [AT-44] Profile page bug fix

- components/ActivityForm.jsx
- components/CreateActivity.jsx
- components/EditActivity.jsx
- components/EditProfile.jsx
- components/NavBar.jsx
- components/ProfileContent.jsx
- src/axiosInstance.js
at-45
- แก้ error ที่ vercel แจ้ง
> [AT-45] fix cant deploy 

- components/EditActivity.jsx
at-46
- แก้ Image กลับเป็น img
> [AT-46] Change Image back to img

- components/CreateActivity.jsx
- components/EditActivity.jsx
- components/ProfileContent.jsx
at-46
- เพิ่ม validate ให้ create และ edit ไม่สามารถเลือกรูปเกิน 10mb ได้ 
- แก้ ข้อความ validate ของ field อื่นให้เป็นสีแดงและตัวเล็กลง
- แก้ bug หน้า profile จาก Image เป็น img
> [AT-46] add image size validate

- components/EditActivity.jsx
- components/EditProfile.jsx
- components/ProfileContent.jsx
[AT-39] improve fetch user, posts's user  api
- implement getUserById API for display user profile
- implement getPostsByUserId API for display all posts's user 
> [AT-39] improve fetch user, posts's user  api

- components/EditProfile.jsx
at-50
- ทำให้ component edituserprofile โชว์รูปที่ user ใช้ และสามารถเปลี่ยนแปลงรูปได้
- ใส่ validation ให้ไม่ให้ user เลิกรูปที่มีขนาดเกิน 10mb
- ใส่ validation ให้ firstname lastname และ city
> [AT-50] Change edit profile to display exist of userImage

- src/axiosInstance.js
at-51
- ทำให้เวลา access token หมดอายุ user จะถูกเด้งออกไปที่หน้า login page 
> [AT-51] handle res401 bring user to login page

- components/EditProfile.jsx
- components/ProfileContent.jsx
at-58, at-54
- เพิ่มฟังชั่นคำนวณ bmi ให้แสดงผลที่หน้า profile อย่างถูกต้อง
- เปลี่ยนข้อมูลใน userprofile จาก user Id ให้แสดงเป็น fullname
- link รูปโปรไฟล์กับ display name ของ การ์ดในเพจ profile ให้ link กับ current user
> [AT-58] implement bmi function and change fullname

- components/ActivityForm.jsx
- components/CardMenu.jsx
- components/CreateActivity.jsx
- components/EditActivity.jsx
- components/EditProfile.jsx
- components/HomeContent.jsx
- components/ProfileContent.jsx
- pages/login.jsx
- pages/register.jsx
- src/axiosInstance.js
- src/userContext.js
> [AT-61] fix bug and something much more
